config/routes.rb
Rails.application.routes.draw do
  resources :next_race

  resources :api_configuration

  root to: 'next_race#index'
end

app/controllers/api_configuration_controller.rb
class ApiConfigurationController < ApplicationController
  before_filter :get_api_information

  def index
  end

  def create
    @api.assign_attributes(
        url: param[:url], key: param[:key]
    )

    if @api.save
      flash[:success] = 'API saved!'
      redirect_to api_configuration_index_path
    else
      render 'index'
    end
  end

  def update
    api = Config::RaceApi.find(params[:id])
    api.live_update = params[:active]
    api.save
    redirect_to api_configuration_index_path
  end

  def destroy
    api = Config::RaceApi.find(params[:id])
    api.destroy
    redirect_to api_configuration_index_path
  end

  private

  def param
    params[:api]
  end

  def get_api_information
    @api = Config::RaceApi.new
    @apis = Config::RaceApi.all
    @request_logs = Logger::ApiRequestLogger.paginate(page: params[:page], per_page: 10).order(id: :desc)
    @logs = Logger::NextRaceLogger.paginate(page: params[:page], per_page: 10).order(id: :desc)
    @threads = WebApi::Tracker.instance.threads
  end
end

app/helpers/api_configuration_helper.rb
module ApiConfigurationHelper
end

app/views/api_configuration/_api_table.html.erb
<h2>External API Resources</h2>
<table class="config_table">
  <thead>
  <tr>
    <th>API Key</th>
    <th>URL</th>
    <th>Tracking</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @apis.each do |api| %>
    <tr>
      <td><%= api.key %></td>
      <td><%= api.url %></td>
      <td><%= check_box_tag(:active, api.live_update, api.live_update, disabled: true) %></td>
      <td>
        <% if api.live_update? %>
           <span class="table_actions"><%= link_to('Dectivate', api_configuration_path(api, {active: false}), method: :put) %></span>
        <% else %>
            <span class="table_actions"><%= link_to('Activate', api_configuration_path(api, {active: true}), method: :put) %></span> |
            <span class="table_actions"><%= link_to('Delete', api_configuration_path(api), method: :delete) %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/api_configuration/_db_transaction_logs.html.erb
<h2>Record Transaction Log</h2>
<table class="request_logs_table">
  <thead>
  <tr>
    <th>Error</th>
    <th>Logged at</th>
  </tr>
  </thead>
  <tbody>
  <% @logs.each do |record| %>
      <tr>
        <td><%= record.error %></td>
        <td><%= record.logged_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @logs, class: 'apple_pagination' %>

app/views/api_configuration/_errors.html.erb
<% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
        <% @api.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/api_configuration/_form.html.erb
<fieldset class="form_fields">
  <legend>New API Resource</legend>

  <%= render partial: 'errors' %>

  <%= form_for :api, method: :post do |f| %>

      <%= f.label :key %>
      <%= f.text_field :key %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <%= f.submit 'Save' %>
  <% end %>
</fieldset>

app/views/api_configuration/_request_logs.html.erb
<h2>Request Logs</h2>
<table class="request_logs_table">
  <thead>
  <tr>
    <th>Time</th>
    <th>Request</th>
    <th>Response Code</th>
    <th>Message</th>
  </tr>
  </thead>
  <tbody>
  <% @request_logs.each do |api| %>
      <tr>
        <td><%= api.created_at %></td>
        <td><%= api.api_request %></td>
        <td><%= api.code %></td>
        <td><%= api.message %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @request_logs, class: 'apple_pagination' %>

app/views/api_configuration/_threads.html.erb
<h2>Threads</h2>
<table class="config_table">
  <thead>
  <tr>
    <th>Thread</th>
    <th>Status</th>
    <th>Alive?</th>
  </tr>
  </thead>
  <tbody>
  <% @threads.each do |thread| %>
      <tr>
        <td><%= thread %></td>
        <td><%= thread.status %></td>
        <td><%= thread.alive? %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/api_configuration/index.html.erb
<%= button_to('Back', root_path, method: :get) %>
<div class="container" id="api_config_container">
  <%= render partial: 'api_table' %>

  <%= render partial: 'form' %>

  <%= render partial: 'threads' %>

  <%= render partial: 'request_logs' %>

  <%= render partial: 'db_transaction_logs' %>
</div>