config/routes.rb
Rails.application.routes.draw do
  resources :next_race

  resources :api_configuration

  root to: 'next_race#index'
end

app/models/web_api/next_race/logger.rb
module WebApi::NextRace::Logger
  MODEL = Logger::NextRaceLogger

  def log_failure(hash)
    MODEL.create(
        error: "object: #{hash[:object].class}, error: #{hash[:error].join(', ')}",
        logged_at: DateTime.now
    )
  end
end

app/models/web_api/next_race/recorder.rb
class WebApi::NextRace::Recorder

  COURSE_MODEL = RaceCourse
  RACE_MODEL = Race
  RUNNER_MODEL = Runner

  def initialize
  end

  def persist_race(params)
    course_hash = create_or_find_course(params['course'])
    return course_hash unless course_hash[:persisted]
    course = course_hash[:object]

    race_hash = create_race(course, params)
    return race_hash unless race_hash[:persisted]
    race = race_hash[:object]

    competitors = create_runners(race, params['runners'])
    race.runners << competitors
    race.requested_at = DateTime.now
    { persisted: race.save, error: race.errors, object: race}
  end

  private

  def create_or_find_course(course_name)
    course = COURSE_MODEL.where(name: course_name).first || COURSE_MODEL.new(name: course_name)
    return {
        persisted: course.save,
        error: course.errors.full_messages,
        object: course
    }
  end

  def create_race(course, params)
    race = course.races.new(
        time: params['time'],
        distance: params['distance']
    )
    return {
        persisted: race.save,
        error: race.errors.full_messages,
        object: race
    }
  end

  def create_runners(race, runners)
    competitors = []
    runners.each do |runner|
      runner = race.runners.new(
          number: runner['number'],
          horse_name: runner['horse_name'],
          jockey_name: runner['jockey_name'],
          form: runner['form'],
          odds: runner['odds']
      )
      competitors << runner
    end
    competitors
  end

end

app/models/web_api/next_race/service.rb
class WebApi::NextRace::Service
  include WebApi::NextRace::Logger
  delegate :next_race_url, to: :api_lookup_klass
  delegate :get_resource, to: :requestor_klass
  delegate :persist_race, to: :recorder_klass

  def initialize
    @url = next_race_url
  end

  def request_next_race
    race_json = get_resource
    result = persist_race(race_json)
    log_failure(result) unless result[:persisted]
    result
  end

  private

  attr_reader :url

  def api_lookup_klass
    @api_lookup_klass ||= Config::RaceApi
  end

  def requestor_klass
    @requestor_klass ||= WebApi::Requestor.new(url)
  end

  def recorder_klass
    @recorder_klass ||= WebApi::NextRace::Recorder.new
  end
end

app/controllers/next_race_controller.rb
class NextRaceController < ApplicationController
  after_filter :respond

  def index
    @race = Race.next_race
    @course = @race.name
    @distance = @race.is_a?(ActiveRecord::Relation) ? '' : @race.furlongs
    @time = @race.is_a?(ActiveRecord::Relation) ? '' : @race.local_time
    @countdown = @race.is_a?(ActiveRecord::Relation) ? '' : @race.minutes_to_start
    @runners = @race.is_a?(ActiveRecord::Relation) ? [] : @race.runners.order_by_odds
  end

  private

  def respond
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/next_race_helper.rb
module NextRaceHelper

  # returns true if the latest race time is 10 minutes or more in the past
  def no_scheduled_race(race)
    return true if race.is_a? ActiveRecord::Relation
    time = race.time
    time.localtime < (Time.now - 10.minutes)
  end

end

app/views/next_race/_no_scheduled_race.html.erb
<div class="race_feed">
  <div class="race_information">
    <ul>
      <h2>Next Race Unavailable</h2>
      <p>There's currently no race information available. This page will be updated when a race has been scheduled.</p>
    </ul>
  </div>
</div>

app/views/next_race/_race_information.html.erb
<% if no_scheduled_race(@race) %>
    <%= render partial: 'no_scheduled_race' %>
<% else %>
    <%= render partial: 'race_widget' %>
<% end %>

app/views/next_race/_race_widget.html.erb
<div class="race_feed">

  <div class="race_information">
    <ul>
      <h2><%= @course %></h2>
      <li ><b>Time:</b> <span id="start_time"><%= @time %></span></li>
      <li><b>Starts in:</b> <span id="count_down"><%= @countdown %> minutes</span></li>
      <li><b>Distance (Furlongs):</b> <%= @distance %></li>
    </ul>

  </div>

  <div class="runners">
    <ul>
      <% @runners.each do |runner| %>
          <li>
            <table class="runner_block" id="<%= runner.id %>">
              <thead>
              <tr>
                <th>No.</th>
                <th>Jockey</th>
                <th>Horse</th>
                <th>Odds</th>
                <th>Form</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><%= runner.number %></td>
                <td><%= runner.jockey_name %></td>
                <td><%= runner.horse_name %></td>
                <td><%= runner.odds %></td>
                <td><%= runner.form %></td>
              </tr>
              </tbody>
            </table>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/next_race/index.html.erb
<%= button_to('Configure API', api_configuration_index_path, method: :get) %>
<div class="container" id="next_race_container">
  <%= render partial: 'race_information' %>
</div>

<div class="spinner" hidden>
  <%= image_tag 'ripple.gif' %>
</div>

app/views/next_race/index.js.erb
$('#next_race_container').html("<%= escape_javascript(render partial: 'race_information') %>");